[package]
name = "xenstore"
version = "0.2.0"
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
edition = "2018"
description = "Rust FFI bindings for libxenstore"
readme = "README.md"
homepage = "https://github.com/Wenzel/xenstore"
repository = "https://github.com/Wenzel/xenstore"
license = "GPL-3.0-only"
keywords = ["xen", "xenstore"]
categories = ["api-bindings"]

[dependencies]
libloading = "0.6.1"
log = "0.4.8"
enum-primitive-derive = "0.1.2"
num-traits = "0.2.11"
xenstore-sys = "0.1.1"
libc = "0.2"
