[package]
name = "xenstore"
version = "0.1.0"
authors = ["Mathieu Tarral <mathieu.tarral@protonmail.com>"]
edition = "2018"
repository = "https://github.com/Wenzel/xenstore"
readme = "README.md"
keywords = ["xen"]
description = "Rust bindings for Xenstore"
license = "GPL-3.0-only"

[dependencies]
libloading = "0.6.1"
log = "0.4.8"
xenstore-sys = { git = "https://github.com/Wenzel/xenstore-sys" }
