name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        subcommand: ['fmt', 'build', 'clippy', 'test']
        include:
            - subcommand: 'clippy'
              # treat warnings as errors
              args: '-- -D warnings'
            - subcommand: 'fmt'
              args: '--check'
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install crate dependencies
        run: sudo apt-get install -y libxen-dev

      - run: cargo ${{ matrix.subcommand }} ${{ matrix.args }}
